[package]
name = "nebula-listener"
version = "0.1.0"
edition = "2024"

[dependencies]
nebula-protocol = { path = "../nebula-protocol" }
nebula-firewall = { path = "../nebula-firewall" }
ipnet = "2.12.0"
libc = "0.2"
tokio = { version = "1.52.3", features = ["net", "rt-multi-thread", "macros", "sync", "time"] }

[dev-dependencies]
tokio = { version = "1.52.3", features = ["full", "test-util"] }
